export default {
  login: "savip",
  id: 14049584,
  node_id: "MDQ6VXNlcjE0MDQ5NTg0",
  avatar_url: "https://avatars0.githubusercontent.com/u/14049584?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/savip",
  html_url: "https://github.com/savip",
  followers_url: "https://api.github.com/users/savip/followers",
  following_url: "https://api.github.com/users/savip/following{/other_user}",
  gists_url: "https://api.github.com/users/savip/gists{/gist_id}",
  starred_url: "https://api.github.com/users/savip/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/savip/subscriptions",
  organizations_url: "https://api.github.com/users/savip/orgs",
  repos_url: "https://api.github.com/users/savip/repos",
  events_url: "https://api.github.com/users/savip/events{/privacy}",
  received_events_url: "https://api.github.com/users/savip/received_events",
  type: "User",
  site_admin: false,
  name: "Pratap",
  company: "Late'start",
  blog: "",
  location: "Australia",
  email: null,
  hireable: null,
  bio: "Learning JS ,ReactJs, Node Js and React native",
  twitter_username: null,
  public_repos: 16,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2015-08-31T06:03:32Z",
  updated_at: "2020-09-09T18:00:28Z"
  }